CouponWeb/Controllers/ProductController.cs
using MangoWeb.Models;
using MangoWeb.Service.Iservice;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ProductWeb.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _ProductService;
        public ProductController(IProductService ProductService)
        {
            _ProductService = ProductService;
        }
        public async Task<ActionResult<IEnumerable<ProductDto>>> ProductIndex()
        {
            List<ProductDto> Products = new();
            var response = await _ProductService.GetAllProducts();
            if (response != null && response.isSuccess)
            {
                Products = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["Error"] = response?.message;
            }
            return View(Products);
        }

        public async Task<IActionResult> ProductCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ProductCreate(ProductDto Product)
        {
            if (ModelState.IsValid)
            {
                var response = await _ProductService.createProduct(Product);
                if (response != null && response.isSuccess)
                {
                    TempData["Success"] = "Product Created Succesfully";
                    return RedirectToAction(nameof(ProductIndex));
                }
                else
                {
                    TempData["Error"] = response?.message;
                }
            }
            return View();
        }
        public async Task<IActionResult> ProductDelete(int ProductId)
        {
            var response = await _ProductService.GetProductById(ProductId);
            if (response != null && response.isSuccess)
            {
                var ProductDto = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(response.Result));
                return View(ProductDto);
            }
            else
            {
                TempData["Error"] = response?.message;
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ProductDelete(ProductDto ProductDto)
        {
            var response = await _ProductService.DeleteProduct(ProductDto.ProductId);
            if (response != null && response.isSuccess)
            {
                TempData["Success"] = "Product Deleted Successfully";
                return RedirectToAction(nameof(ProductIndex));
            }
            else
            {
                TempData["Error"] = response?.message;
            }
            return View(ProductDto);
        }
		public async Task<IActionResult> ProductEdit(int productId)
		{
			ResponseDto? response = await _ProductService.GetProductById(productId);

			if (response != null && response.isSuccess)
			{
				ProductDto? model = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(response.Result));
				return View(model);
			}
			else
			{
				TempData["error"] = response?.message;
			}
			return NotFound();
		}

		[HttpPost]
		public async Task<IActionResult> ProductEdit(ProductDto productDto)
		{
			if (ModelState.IsValid)
			{
				ResponseDto? response = await _ProductService.UpdateProduct(productDto);

				if (response != null && response.isSuccess)
				{
					TempData["Success"] = "Product updated successfully";
					return RedirectToAction(nameof(ProductIndex));
				}
				else
				{
					TempData["Error"] = response?.message;
				}
			}
			return View(productDto);
		}
	}
}

CouponWeb/Views/Product/ProductCreate.cshtml
@model ProductDto
<form asp-action="ProductCreate">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Create Product</h1>

        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Name</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">CategoryName</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Description</label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">ImageUrl</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Price</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger" />
            </div>

            <div class="col-5 offset-2">
                <a asp-controller="Product" asp-action="ProductIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>

        </div>

        <div>
        </div>
    </div>
</form>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
            }

CouponWeb/Views/Product/ProductDelete.cshtml
@model ProductDto

<form asp-action="ProductDelete">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Edit Product</h1>
        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Name</label>
            </div>
            <input hidden asp-for="ProductId" />
            <div class="col-10 pb-3">
                <input asp-for="Name" readonly="true" class="form-control" />@* use readonly instead of disabled
                                                                               as post action will not work.*@
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">CategoryName</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="CategoryName" readonly="true" class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Description</label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Description" disabled rows="5" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">ImageUrl</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageUrl" disabled class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Price</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Price" disabled class="form-control" />
                <span asp-validation-for="Price" class="text-danger" />
            </div>

            <div class="col-5 offset-2">
                <a asp-controller="Product" asp-action="ProductIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>

        </div>

        <div>
        </div>
    </div>
</form>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
            }

CouponWeb/Views/Product/ProductEdit.cshtml
@model ProductDto
<form asp-action="ProductEdit">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Edit Product</h1>
        <hr />
        <div class="row">
            <input hidden asp-for="ProductId" />
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Name</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">CategoryName</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Description</label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">ImageUrl</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Price</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger" />
            </div>

            <div class="col-5 offset-2">
                <a asp-controller="Product" asp-action="ProductIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-Success form-control" />
            </div>

        </div>

        <div>
        </div>
    </div>
</form>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
            }

CouponWeb/Views/Product/ProductIndex.cshtml
@model IEnumerable<ProductDto>
<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white">Products List</h1>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a asp-action="ProductCreate" asp-controller="Product" class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Create New Product</a>
			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>
						Name
					</th>
					<th>
						Category Name
					</th>
					<th>
						Price
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@item.Name
						</td>
						<td>
							@item.CategoryName
						</td>
						<td>
							@item.Price
						</td>
						<td>
							<a asp-action="ProductEdit" asp-route-productId="@item.ProductId" class="btn btn-success">
								<i class="bi bi-pencil-square"></i>
							</a>
							<a asp-action="ProductDelete" asp-route-productId="@item.ProductId" class="btn btn-danger">
								<i class="bi bi-trash"></i>
							</a>
						</td>
					</tr>
				}
			</tbody>
		</table>

	</div>

</div>