CouponWeb/Controllers/CouponController.cs
using MangoWeb.Models;
using MangoWeb.Service.Iservice;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;

namespace MangoWeb.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }
        public async Task<IActionResult> CouponIndex()
        {
            List<CouponDto> coupons = new();
            var response = await _couponService.GetAllCoupon();
            if (response != null && response.isSuccess)
            {
                coupons = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["Error"] = response?.message;
            }
            return View(coupons);
        }
        public async Task<IActionResult> CouponCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CouponCreate(CouponDto coupon)
        {
            if (ModelState.IsValid)
            {
                var response =await _couponService.createCoupon(coupon);
                if (response != null && response.isSuccess)
                {
                    TempData["Success"] = "Coupon Created Succesfully";
                    return RedirectToAction(nameof(CouponIndex));
                }
                else
                {
                    TempData["Error"] = response?.message;
                }
            }
            return View();
        }

		public async Task<IActionResult> CouponDelete(int CouponId)
        {
            var response = await _couponService.GetCouponById(CouponId);
            if (response != null && response.isSuccess)
            {
                CouponDto? couponDto = JsonConvert.DeserializeObject<CouponDto>(Convert.ToString(response.Result));
                return View(couponDto);
            }
            else
            {
                TempData["Error"] = response?.message;
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CouponDelete(CouponDto CouponDto)
        {
            var response = await _couponService.DeleteCoupon(CouponDto.CouponId);
            if (response != null && response.isSuccess)
            {
                TempData["Success"] = "Coupon Deleted Successfully";
                return RedirectToAction(nameof(CouponIndex));
            }
            else
            {
                TempData["Error"] = response?.message;
            }
            return View(CouponDto);
        }
    }
}

CouponWeb/Views/Coupon/CouponCreate.cshtml
@model CouponDto
<form asp-action="CouponCreate">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Create Coupon</h1>

        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Coupon Code</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="CouponCode" class="form-control" />
                <span asp-validation-for="CouponCode" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Discount Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="DiscountAmount" class="form-control" />
                <span asp-validation-for="DiscountAmount" class="text-danger" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Min Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="MinAmount" class="form-control" />
                <span asp-validation-for="MinAmount" class="text-danger" />
            </div>

            <div class="col-5 offset-2">

                <a asp-controller="Coupon" asp-action="CouponIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />

            </div>

        </div>

        <div>
        </div>
    </div>
</form>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
            }

CouponWeb/Views/Coupon/CouponDelete.cshtml
@model CouponDto
<form asp-action="CouponDelete">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Delete Coupon</h1>
        <input asp-for="CouponId" hidden />
        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Coupon Code</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="CouponCode" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Discount Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="DiscountAmount" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Min Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="MinAmount" disabled class="form-control" />
            </div>

            <div class="col-5 offset-2">

                <a asp-controller="Coupon" asp-action="CouponIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-success form-control" />
            </div>

        </div>

        <div>
        </div>
    </div>
</form>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
            }

CouponWeb/Views/Coupon/CouponIndex.cshtml
@model IEnumerable<CouponDto>
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white">Coupons List</h1>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller ="Coupon" asp-action="CouponCreate" class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Create New Coupon</a>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Coupon Code
                    </th>
                    <th>
                        Discount Amount
                    </th>
                    <th>
                        Minimum Amount
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var coupon in Model)
                {
                    <tr>
                        <td>
                            @coupon.CouponCode
                        </td>
                        <td>
                            @(coupon.DiscountAmount.ToString("C"))
                        </td>
                        <td>
                            @(coupon.MinAmount.ToString("C"))
                        </td>
                        <td>
                            <a asp-action ="CouponDelete" asp-route-CouponID="@coupon.CouponId" class="btn btn-danger">
                                <i class="bi bi-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>

</div>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
            }